---
title: "WINAMP - Unknown Artist"
sidebar: false 
---

MUY660-İş Analitiği dersi takım sayfamıza hoş geldiniz.

Malesef adımları doğru yaptığımızı düşünmemize rağmen sayfayı bir türlü düzenlenen şekilde yayınlayamıyoruz. Hep aynı sayfa çıkıyor :(

Neyse şimdi çözdük gibi :)

## Takım

1.  [Utku ORUN](/takim/utkuorun.qmd)

2.  [Haydar GULTEKIN](/takim/HaydarGULTEKIN.qmd)

3.  [Frederico Rodrigues de Paula Santos](/takim/fred.qmd)

4.  [Sebastian Szymański](/takim/szymanski.qmd)

## Proje Adı

MUY660-İş Analitiği iyileştirme çalışmaları (örnek)

## Proje Konusu

Örnek: Bu projede MUY660-İş Analitiği ders içeriğinin analitik yaklaşımlarla iyileştirilmesini hedefledik. Bu doğrultuda tüm üniversitelerdeki benzer derslerin verisini toplayarak bir veri seti oluşturduk Analiz için ........ yöntemleri kullanarak, ....... çalışmaları yaptık Sonuç olarak, MUY660-İş Analitiği dersinin dünyadaki tüm derslerden daha iyi olduğunu ve bu dersi aldığımız için çok mutlu olduğumuzu tespit ettik.

## Veri Seti Hakkında Özet Bilgi

## Sonuçlar

Burada key takeways verilmelidir. En az 3 en fazla 5 madde ile çarpıcı sonuçlar sunulmalıdır.
