---
title: "Proje Unknown Artist"
number-sections: true
---

**Proje sayfamıza hoş geldiniz.**

*TÜRKİYE İLLERİNDE 2023 YILINDA GERÇEKLEŞEN TOPLAM KONUT SATIŞLARI ANALİZİ*

# Proje Genel Bakış ve Kapsamı

Projemizde Türkiye'de 2023 yılında gerçekleşen toplam konut satışlarının illere göre analizi yapılmıştır.

# Veri

```{r}
library(readxl)
veri <- read_excel("C:/Users/Pc/Desktop/2023KONUT.xlsx")
print(veri)

```

## 

```         
```

## Veri Kaynağı

Projemiz için elde ettiğimiz verinin kaynağı Türkiye İstatistik Kurumu web sitesidir.

Detay için bkz. "https://biruni.tuik.gov.tr/ilgosterge/?locale=tr"

## Veri Hakkında Genel Bilgiler

xxxxxx

## Tercih Sebebi

Türkiye'deki konut satışlarının illere göre karşılaştırılması ve konut sirkülasyonunun net bir şekilde analiz edilebilmesine olanak tanınması, bu veri setinin tercih edilmesinde büyük önem taşımaktadır. Ayrıca 6 Şubat 2023 yılında gerçekleşen deprem felaketinin ardından zarar gören 11 ildeki konut satışlarının ne derece etkilendiğini görebilmek adına veri seti ilgi çekici bulunmuştur.

## Ön İşleme

R studio'nun dış kaynaktan .xlsx veya .csv formatında verileri okuyabilmesi için ilk etapta "readxl" paketi yüklenmiştir. Web sitesinden indirilen excel formatındaki ham veri R studio'nun okuyamayacağı türden tablolar içermektedir. Ayrıca R studio'nun okuyamadağı Türkçe karakterler ve sayı formatları yeniden işlenmiş ve yeni bir dosya olarak kaydedildikten sonra okutulmuştur.

# Analiz

xxxxxx

## Keşifsel Veri Analizi

xxxxxx

## Trend Analizi

xxxxxx

## Model Uydurma

xxxxxx

## Sonuçlar

xxxxxx

# Sonuçlar ve Ana Çıkarımlar

xxxxxx
